---
- hosts: ubuntu
  become: yes
  gather_facts: false
  tasks:
   - name: install apche2
     package:
      name: apache2
      state: present
   - name: restart apache
     service:
      name: apache2
      state: restarted
   - name: copy index file
     copy:
      src: /root/index.html
      dest: /var/www/html    
