---
- hosts: all
  become: yes
  gather_facts: true
  tasks:
   - name: install tomcat8
     apt:
      name: tomcat8
      state: latest
     when: ansible_distribution== 'Ubuntu'
     notify:
       - start tomcat8
   - name: install tomcat
     yum:
      name: tomcat
      state: latest
     when: ansible_distribution== 'CentOS'
     notify:
       - start tomcat
   - name: get the file from remote 
     get_url:
      url: https://tomcat.apache.org/tomcat-7.0-doc/appdev/sample/sample.war
      dest: /var/lib/tomcat/webapps
  handlers: 
   - name: start tomcat8
     service:
      name: tomcat8
      state: restarted
   - name: start tomcat
     service:
      name: tomcat
      state: restarted    
